[pytest]
timeout = 25000
markers =
    home_page: UI tests for home page
    dynamic_id_page: UI tests for dynamic id page
    class_attribute_page: UI tests for class attribute page
    hidden_layers_page: UI tests for Hidden Layers page
    load_delays_page: UI tests for Load Delays page
    ajax_data_page: UI tests for AJAX Data page
    client_side_delay_page: UI tests for Client Side Delay page
    click_page: UI tests for Click page